export interface City {
  code: string; 
  prefectureCode: string;
  ja: string;
  en: string;
}

export const cities: City[] = [
  { code: "0101", prefectureCode: "01", ja: "札幌市", en: "Sapporo" },
  { code: "0102", prefectureCode: "01", ja: "函館市", en: "Hakodate" },
  { code: "0201", prefectureCode: "02", ja: "青森市", en: "Aomori" },
  { code: "0301", prefectureCode: "03", ja: "盛岡市", en: "Morioka" },
  { code: "0401", prefectureCode: "04", ja: "仙台市", en: "Sendai" },
  { code: "0501", prefectureCode: "05", ja: "秋田市", en: "Akita" },
  { code: "0601", prefectureCode: "06", ja: "山形市", en: "Yamagata" },
  { code: "0701", prefectureCode: "07", ja: "福島市", en: "Fukushima" },
  { code: "0801", prefectureCode: "08", ja: "水戸市", en: "Mito" },
  { code: "0901", prefectureCode: "09", ja: "宇都宮市", en: "Utsunomiya" },
  { code: "1001", prefectureCode: "10", ja: "前橋市", en: "Maebashi" },
  { code: "1101", prefectureCode: "11", ja: "さいたま市", en: "Saitama" },
  { code: "1201", prefectureCode: "12", ja: "千葉市", en: "Chiba" },
  { code: "1301", prefectureCode: "13", ja: "新宿区", en: "Shinjuku" },
  { code: "1302", prefectureCode: "13", ja: "渋谷区", en: "Shibuya" },
  { code: "1303", prefectureCode: "13", ja: "港区", en: "Minato" },
  { code: "1401", prefectureCode: "14", ja: "横浜市", en: "Yokohama" },
  { code: "1402", prefectureCode: "14", ja: "川崎市", en: "Kawasaki" },
  { code: "1501", prefectureCode: "15", ja: "新潟市", en: "Niigata" },
  { code: "1601", prefectureCode: "16", ja: "富山市", en: "Toyama" },
  { code: "1701", prefectureCode: "17", ja: "金沢市", en: "Kanazawa" },
  { code: "1801", prefectureCode: "18", ja: "福井市", en: "Fukui" },
  { code: "1901", prefectureCode: "19", ja: "甲府市", en: "Kofu" },
  { code: "2001", prefectureCode: "20", ja: "長野市", en: "Nagano" },
  { code: "2101", prefectureCode: "21", ja: "岐阜市", en: "Gifu" },
  { code: "2201", prefectureCode: "22", ja: "静岡市", en: "Shizuoka" },
  { code: "2202", prefectureCode: "22", ja: "浜松市", en: "Hamamatsu" },
  { code: "2301", prefectureCode: "23", ja: "名古屋市", en: "Nagoya" },
  { code: "2401", prefectureCode: "24", ja: "津市", en: "Tsu" },
  { code: "2501", prefectureCode: "25", ja: "大津市", en: "Otsu" },
  { code: "2601", prefectureCode: "26", ja: "京都市", en: "Kyoto" },
  { code: "2701", prefectureCode: "27", ja: "大阪市", en: "Osaka" },
  { code: "2702", prefectureCode: "27", ja: "堺市", en: "Sakai" },
  { code: "2801", prefectureCode: "28", ja: "神戸市", en: "Kobe" },
  { code: "2802", prefectureCode: "28", ja: "姫路市", en: "Himeji" },
  { code: "2901", prefectureCode: "29", ja: "奈良市", en: "Nara" },
  { code: "3001", prefectureCode: "30", ja: "和歌山市", en: "Wakayama" },
  { code: "3101", prefectureCode: "31", ja: "鳥取市", en: "Tottori" },
  { code: "3201", prefectureCode: "32", ja: "松江市", en: "Matsue" },
  { code: "3301", prefectureCode: "33", ja: "岡山市", en: "Okayama" },
  { code: "3401", prefectureCode: "34", ja: "広島市", en: "Hiroshima" },
  { code: "3501", prefectureCode: "35", ja: "山口市", en: "Yamaguchi" },
  { code: "3601", prefectureCode: "36", ja: "徳島市", en: "Tokushima" },
  { code: "3701", prefectureCode: "37", ja: "高松市", en: "Takamatsu" },
  { code: "3801", prefectureCode: "38", ja: "松山市", en: "Matsuyama" },
  { code: "3901", prefectureCode: "39", ja: "高知市", en: "Kochi" },
  { code: "4001", prefectureCode: "40", ja: "福岡市", en: "Fukuoka" },
  { code: "4002", prefectureCode: "40", ja: "北九州市", en: "Kitakyushu" },
  { code: "4101", prefectureCode: "41", ja: "佐賀市", en: "Saga" },
  { code: "4201", prefectureCode: "42", ja: "長崎市", en: "Nagasaki" },
  { code: "4301", prefectureCode: "43", ja: "熊本市", en: "Kumamoto" },
  { code: "4401", prefectureCode: "44", ja: "大分市", en: "Oita" },
  { code: "4501", prefectureCode: "45", ja: "宮崎市", en: "Miyazaki" },
  { code: "4601", prefectureCode: "46", ja: "鹿児島市", en: "Kagoshima" },
  { code: "4701", prefectureCode: "47", ja: "那覇市", en: "Naha" },
];