/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/Login'
import { Route as AuthUnauthorizedRouteImport } from './routes/_auth/Unauthorized'
import { Route as ProtectedAdminPanelRouteImport } from './routes/_protected/AdminPanel'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/Dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/_auth/Unauthorized',
  path: '/Unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminPanelRoute = ProtectedAdminPanelRouteImport.update({
  id: '/_protected/AdminPanel',
  path: '/AdminPanel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/_protected/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof AuthLoginRoute
  '/Unauthorized': typeof AuthUnauthorizedRoute
  '/AdminPanel': typeof ProtectedAdminPanelRoute
  '/Dashboard': typeof ProtectedDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof AuthLoginRoute
  '/Unauthorized': typeof AuthUnauthorizedRoute
  '/AdminPanel': typeof ProtectedAdminPanelRoute
  '/Dashboard': typeof ProtectedDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/Login': typeof AuthLoginRoute
  '/_auth/Unauthorized': typeof AuthUnauthorizedRoute
  '/_protected/AdminPanel': typeof ProtectedAdminPanelRoute
  '/_protected/Dashboard': typeof ProtectedDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Login' | '/Unauthorized' | '/AdminPanel' | '/Dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Login' | '/Unauthorized' | '/AdminPanel' | '/Dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth/Login'
    | '/_auth/Unauthorized'
    | '/_protected/AdminPanel'
    | '/_protected/Dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  ProtectedAdminPanelRoute: typeof ProtectedAdminPanelRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/Login': {
      id: '/_auth/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/Unauthorized': {
      id: '/_auth/Unauthorized'
      path: '/Unauthorized'
      fullPath: '/Unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/AdminPanel': {
      id: '/_protected/AdminPanel'
      path: '/AdminPanel'
      fullPath: '/AdminPanel'
      preLoaderRoute: typeof ProtectedAdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/Dashboard': {
      id: '/_protected/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  ProtectedAdminPanelRoute: ProtectedAdminPanelRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
